// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQz-9y1ay96_VN5uEQmjbi4z7WxB9rLo',
    appId: '1:532922145349:web:f5389f70f7371edbb8a12c',
    messagingSenderId: '532922145349',
    projectId: 'shopaflow',
    authDomain: 'shopaflow.firebaseapp.com',
    storageBucket: 'shopaflow.firebasestorage.app',
    measurementId: 'G-0ZXEBBRRY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_jVler66XPNfEXDmTcYOVdEsEHKdwMs4',
    appId: '1:532922145349:android:d53d9f5c9b22309ab8a12c',
    messagingSenderId: '532922145349',
    projectId: 'shopaflow',
    storageBucket: 'shopaflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9cAeUdtXSF9XVpAYN--xHGaJ3VK5x_BY',
    appId: '1:532922145349:ios:6702ce0b11038115b8a12c',
    messagingSenderId: '532922145349',
    projectId: 'shopaflow',
    storageBucket: 'shopaflow.firebasestorage.app',
    iosBundleId: 'com.shopaflowios.aoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9cAeUdtXSF9XVpAYN--xHGaJ3VK5x_BY',
    appId: '1:532922145349:ios:eeea28a6030032acb8a12c',
    messagingSenderId: '532922145349',
    projectId: 'shopaflow',
    storageBucket: 'shopaflow.firebasestorage.app',
    iosBundleId: 'com.shopamac.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQz-9y1ay96_VN5uEQmjbi4z7WxB9rLo',
    appId: '1:532922145349:web:08590db86d2fac49b8a12c',
    messagingSenderId: '532922145349',
    projectId: 'shopaflow',
    authDomain: 'shopaflow.firebaseapp.com',
    storageBucket: 'shopaflow.firebasestorage.app',
    measurementId: 'G-N27T6NBDLK',
  );
}
